### ISSUE TITLE
Friendlier docker compose project name

### ISSUE THREAD

**Issue by mathroc** [loft-sh/devpod#1514]
**Is your feature request related to a problem?**  

When multiple devpod projects are running if we list the docker compose project by their name they are not very descriptive. so it's not easy to tell which is which

**Which solution do you suggest?**  

It would be nice if it included the full (slugified) devcontainer project name (or the COMPOSE_PROJECT_NAME)

**Which alternative solutions exist?**  

**Additional context**

**Comment by mkvlrn** [comment]
Been banging my head trying to figure this out. vscode's extension accepts `COMPOSE_PROJECT_NAME` and it uses the correct value, for example:

```yaml
services:
  devcontainer:
    container_name: devcontainer_${COMPOSE_PROJECT_NAME}
    image: ghcr.io/mkvlrn/arch-devcontainer:latest
    env_file:
      - ./.devcontainer/.env
    volumes:
      - .:/code/${COMPOSE_PROJECT_NAME}:cached
    command: sleep infinity
```

If repo directory is /home/user/somerepo, then container name should be `devcontainer_somerepo` and repo should be mounted to `/code/somerepo`. This is the behavior of vscode's extension, while devpod gives me something like `devcontainer_default-ar-3e6a0` and `/code/default-ar-3e6a0`.

Maybe reopen? Or adjust documentation for a way to achieve this?

EDIT: Coming across this issue exactly 1 year after OP did is kind of uncanny.
