### ISSUE TITLE
docker compose workspace missing

### ISSUE THREAD

**Issue by abdulari** [loft-sh/devpod#1849]
Hi.
I'm currently trying to mount Intel integrated GPU to DevPod workspace. The mounted GPU is working as expected when I start devpod workspace using docker compose on WSL2. I will definitely create a PR once the code ready.

my question is, 
In docker compose, how can I correctly mount the workspace ? the current implementation is showing a blank workspace. I expect that (at least) devcontainer.json will be present in the workspace folder. 

fyi:
i added a docker volume `devcontainer_volume`  and it mount a blank volume (as expected).
i'm still missing the `devcontainer.json` and `compose.yaml` in my workspace

``` JSON
# devcontainer.json
{
    "dockerComposeFile": "compose.yaml",
    "service": "devcontainer",
    "containerEnv": {
        "HTTP_PROXY":"REDACTED",
        "HTTPS_PROXY":"REDACTED",
        "NO_PROXY":"REDACTED",
        "http_proxy":"REDACTED",
        "htps_proxy":"REDACTED",
        "no_proxy":"REDACTED",
        "WS":"/workspaces"
    },
    "workspaceFolder": "/workspaces",
    "containerUser":"root",
    "remoteUser":"root"
}
```

``` YAML
# compose.yaml
version: '3.8'
services:
  devcontainer:
    image: intelanalytics/ipex-llm-xpu:latest
    command: sleep infinity
    privileged: true
    shm_size: 16G
    devices:
      - /dev/dri
    volumes:
      - devcontainer_volume:/workspaces
      - /usr/lib/wsl:/usr/lib/wsl

volumes:
  devcontainer_volume:
```
