### ISSUE TITLE
fatal agent error: devcontainer up: start container: build and extend docker-compose

### ISSUE THREAD

**Issue by mrdev023** [loft-sh/devpod#298]
**What happened?**

fatal agent error: devcontainer up: start container: build and extend docker-compose: inspect image base: get image config remotely: retrieve image base: GET [https://index.docker.io/v2/library/base/manifests/latest:](https://index.docker.io/v2/library/base/manifests/latest:) UNAUTHORIZED: authentication required; \[map\[Action:pull Class: Name:library/base Type:repository\]\]

**What did you expect to happen instead?**

Work

**How can we reproduce the bug?** (as minimally and precisely as possible)

My `devcontainer.json`:

```
{
  "name": "Ruby",
  "workspaceFolder": "/app",
  "dockerComposeFile": [
    "../docker-compose.yml",
    "../docker/docker-compose.local.yml"
  ],
  "service": "web",
  "forwardPorts": [
    3000
  ],
  "customizations": {
    "vscode": {
      "settings": {},
      "extensions": []
    }
  }
}
```

My `docker-compose.yml`:

```
version: "3.4"

services:
  web:
    restart: always
    image: "ruby:latest"
 [...]
```

**Local Environment:**

* DevPod Version: v0.1.4
* Operating System: linux
* ARCH of the OS: AMD64

**DevPod Provider:**

* Local/remote provider: docker

**Comment by lizardruss** [comment]
@mrdev023 Thanks for surfacing this issue. I attempted to reproduce, but maybe some additional context was left out from `docker/docker-compose.local.yml` or perhaps other services in `docker-compose.yml`

On the surface it seems like an authentication issue pulling the `base:latest` image, but I don't see that in the config.

Here's what I've tried to reproduce:
.devcontainer/devcontainer.json
```json
{
  "name": "Ruby",
  "workspaceFolder": "/app",
  "dockerComposeFile": [
    "../docker-compose.yaml",
    "../docker-compose.local.yaml"
  ],
  "service": "web",
  "forwardPorts": [
    3000
  ],
  "customizations": {
    "vscode": {
      "settings": {},
      "extensions": []
    }
  }
}
```

docker-compose.yaml
```yaml
version: "3.4"

services:
  web:
    restart: always
    image: "ruby:latest"
```

docker-compose.local.yaml
```yaml
version: "3.4"

services:
  web:
    command: sleep infinity
```
