### ISSUE TITLE
devpod-cli build does not take image from compose file

### ISSUE THREAD

**Issue by Pro** [loft-sh/devpod#606]
**What happened?**  

I have a DevContainer setup using docker compose.
The docker compose file also includes build section to build the image.

Using the following build command, I get an error:

```shell
devpod-cli build $(pwd) --repository my_dummy_repo --skip-push
```

```
15:20:21 info Building devcontainer...
15:20:21 error Error building image: build image: get image build info: get image config remotely: parse reference : could not parse reference:
15:20:21 info build: build image: get image build info: get image config remotely: parse reference : could not parse reference: 
```

If I run the exact same setup directly in the DevPod UI, it spins up the container + IDE.

**Manual workaround**

The workaround is to first parse the image from the compose file, and pass it to build:

```shell
dev_service=$(sed '/^[[:blank:]]*#/d;s/\/\/.*//' .devcontainer/devcontainer.json | jq -r ".service")
compose_image=$(cat .devcontainer/docker-compose.yaml | yq .services.$dev_service.image)
devpod-cli build $(pwd) --repository my_dummy_repo --skip-push --devcontainer-image $compose_image 
```

**What did you expect to happen instead?**  

`devpod-cli build` should take the image from the docker compose file of the referenced service.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```json
{
    "name": "Test Compose Build",
    "dockerComposeFile": [
        "docker-compose.yaml"
    ],
    "service": "hello-world-service",
    "customizations": {
        "devpod": {
            "prebuildRepository": "my_hello_world_dev"
        }
    }
}
```

My *`docker-compose.yaml`*:

```yaml
services:
  hello-world-service:
    image: my_hello_world:latest
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
```

My *`Dockerfile`*:

```Dockerfile
FROM ubuntu:22.04

RUN apt update && apt install -y curl
RUN echo "Hello World"
```

**Local Environment:**  
- DevPod Version: 0.3.4
- Operating System: linux 
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker

**Anything else we need to know?**  

No
