### ISSUE TITLE
how to mount a configmap into a container in DevPod?

### ISSUE THREAD

**Issue by yangluoshen** [loft-sh/devpod#627]
**Is your feature request related to a problem?**  
My projects  are deployed on kubernetes, so I choose kuberntes provider(I try this example [examples/simple-k8s-provider/provider.yaml](https://github.com/loft-sh/devpod/blob/main/examples/simple-k8s-provider/provider.yaml)).  
While my project depend on some configs which implement by configmap.
Generate this  configmap is a little complicated, so I don't want to generate it on my local machine. A elegant way is mount configmap (present on k8s already) to workspace, so I can use it easily.

**Which solution do you suggest?**  
a way to mount configmap into workspace

**Which alternative solutions exist?**  

**Additional context**

**Comment by pascalbreuninger** [comment]
Hi @yangluoshen, you can configure your kubernetes provider to use a custom pod manifest, including custom volumes:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: devpod # make sure to use this name
      image: busybox:latest # doesn't matter
      volumeMounts:
        - name: cm-volume
          mountPath: /etc/config
  volumes:
    - name: cm-volume
      configMap:
        name: my-config-map
```
then update/add your kubernets provider 
`devpod provider set-options --option=POD_MANIFEST_TEMPLATE=$(realpath $YOUR_POD_YAML)`
