### ISSUE TITLE
Errors until broken pipe after ssh into my devpod

### ISSUE THREAD

**Issue by rafilkmp3** [loft-sh/devpod#869]
**What happened?**  
When I try to run a devpod, doesn't matter if it is one of the basic examples repositories or custom repositories, I can use it like a charm on vscode, and it's connection never seems to break (no inactivity timeout set up), however, if I try to ssh inside my devpod and install anything like k9s or helm templates, I keep getting error until my pipe is broken and the connection breaks, making me unable to ssh in again unless I stop the devpod and restart it.

**What did you expect to happen instead?**  
I expected to ssh in, install any packages i'd like to and use it normally inside the ssh for anything, like a helm template.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
- Create a devpod on a kubernetes provider based on a EKS environment
- Create any workspace example available using the provider you've created
- Try to input a few commands on ssh.{$WORKSPACE.devpod)
- Expect | session failed to exit: EOF | Error tunneling to container: Process exited with status 137 | 11:45:59 fatal tunnel to container: run in container: wait: remote command exited without exit status or exit signal |

**Local Environment:**  
- DevPod Version: `devpod 0.4.2`
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Cloud Provider: aws
- Kubernetes Provider: v1.28.4
- Local/remote provider: ssh
- Custom provider: provide imported `provider.yaml` config file

```
contexts:
  default:
    defaultIde: vscode
    defaultProvider: kubernetes
    providers:
      aws:
        creationTimestamp: "2024-01-10T13:44:04Z"
      kubernetes:
        creationTimestamp: "2024-01-11T13:57:00Z"
        initialized: true
        options:
          CLUSTER_ROLE:
            userProvided: true
          CREATE_NAMESPACE:
            userProvided: true
            value: "true"
          DISK_SIZE:
            userProvided: true
            value: 10Gi
          DOCKERLESS_DISABLED:
            userProvided: true
            value: "false"
          DOCKERLESS_IMAGE:
            userProvided: true
          HELPER_IMAGE:
            userProvided: true
          HELPER_RESOURCES:
            userProvided: true
          INACTIVITY_TIMEOUT:
            userProvided: true
          KUBECTL_PATH:
            userProvided: true
            value: kubectl
          KUBERNETES_CONFIG:
            userProvided: true
            value: /Users/rafael.sathler/.kube/config
          KUBERNETES_CONTEXT:
            userProvided: true
            value: {CLASSIFIED}
          KUBERNETES_NAMESPACE:
            userProvided: true
            value: devpod
          KUBERNETES_PULL_SECRETS_ENABLED:
            userProvided: true
            value: "true"
          LABELS:
            userProvided: true
          NODE_SELECTOR:
            userProvided: true
          POD_MANIFEST_TEMPLATE:
            userProvided: true
          PVC_ACCESS_MODE:
            userProvided: true
          RESOURCES:
            userProvided: true
            value: requests.cpu=2500m,limits.cpu=3000m
          SERVICE_ACCOUNT:
            userProvided: true
          STORAGE_CLASS:
            userProvided: true
        singleMachine: true
defaultContext: default
```
