### ISSUE TITLE
Port forwarding is not working

### ISSUE THREAD

**Issue by AnhQuanTrl** [loft-sh/devpod#871]
**What happened?**  
I could not access a forwarded port from a postgres container using docker-compose and devpod.

**What did you expect to happen instead?**  
I should be able to access the forwarded port (5432) at localhost.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
  "dockerComposeFile": "docker-compose.devcontainer.yml",
  "service": "app",
  "runServices": ["db"],
  "workspaceFolder": "/workspaces",
  "forwardPorts": [1337, "db:5432"]
}
```

My *`docker-compose.devcontainer.yml`*:
```
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: devcontainer.Dockerfile
    env_file:
      - .env

    volumes:
      - .:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
      - 
volumes:
  postgres-data:
```
*`devcontainer.Dockerfile`* is just `FROM mcr.microsoft.com/devcontainers/javascript-node`.

**Local Environment:**  
- DevPod Version: v0.4.2
- Operating System: linux
- ARCH of the OS: AMD64

**DevPod Provider:**  
- Local/remote provider: docker

**Anything else we need to know?**  
I can access the db with port 5432 inside the app container.
However, I cannot access the db using port forward from the host.
I also don't use VSCode, if that helps. I just install neovim directly inside the workspace container.
