### ISSUE TITLE
Devcontainer with features gets rebuilt every time it is restarted

### ISSUE THREAD

**Issue by IgnisDa** [loft-sh/devpod#904]
**What happened?**  

I have a devcontainer with a few features. When, I stop the container using the "Stop" button in the app, the devcontainer is lost somehow. So that the next time I start it again, all the features are re-evaluated and re-run.

**What did you expect to happen instead?**  

I expect it to work like the vscode devcontainers plugin does. Once a devcontainer with features has been built, I do not want it to be re-built unless explicitly done otherwise.

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```json
{
	"name": "name",
	"dockerComposeFile": "docker-compose.yml",
	"service": "devcontainer",
	"workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",
	"features": {
		"ghcr.io/devcontainers/features/node:1": {},
		"ghcr.io/devcontainers/features/java:1": {
			"version": "17",
			"installMaven": "false",
			"installGradle": "true"
		},
		"ghcr.io/devcontainers-contrib/features/kotlin-sdkman:2": {
			"jdkVersion": "17"
		},
		"ghcr.io/meaningful-ooo/devcontainer-features/fish:1": {}
	}
}
```

My *`docker-compose.yml`*:
```yml
version: "3.8"

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/java:1-17-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
```

**Local Environment:**  
- DevPod Version: v0.5.1
- Operating System: Arch Linux
- ARCH of the OS: ARM64 

**DevPod Provider:**
- Local/remote provider: docker

**Anything else we need to know?**  

It works as expected with the vscode devcontainer plugin.
