### ISSUE TITLE
Devpod Kubernetes Provider - Using persistent volume claim

### ISSUE THREAD

**Issue by cakriwut** [loft-sh/devpod#945]
**Is your feature request related to a problem?**  
We need to be able to reattached PV created by devpod. When we delete workspace, we cannot re-attach PV to the a new workspace. It always recreate PVC using same name as the pod name. 

**Which solution do you suggest?**  
Allow to specify PVC in custom pod manifest. When the devpod volume exists, then devpod should not try to create PVC, but instead just use the template. Example of proposed solution, 

```yaml
# POD TEMPLATE
apiVersion: v1
kind: Pod
metadata:
  name: pod-template
spec:
  containers:
    - name: devpod      
      volumeMounts:
        - mountPath: /workspaces/.home
          name: devpod
          subPath: devpod/home
  volumes:
  - name: devpod
    persistentVolumeClaim:
      claimName: developer-own-pvc

```

**Which alternative solutions exist?**  

**Additional context**
