### ISSUE TITLE
docker compose `include` not supported

### ISSUE THREAD

**Issue by navneetkarnani** [loft-sh/devpod#952]
**What happened?**  

[03:12:34] info (root) Additional property include is not allowed
[03:12:34] info load docker compose project

**What did you expect to happen instead?**  

compose project to be correctly used

**How can we reproduce the bug?** (as minimally and precisely as possible)  

My *`devcontainer.json`*:
```
{
    "name": "mydev",
    "dockerComposeFile": ["docker-compose.lb.yml"],
}
```

My `docker-compose.lb.yml`
```
include:
  - docker-compose.base.yml
 services:
  loadbalancer:
     image: caddy:2-alpine
```

My `docker-compose.base.yml`
```
services:
  app:
    image: eclipse-temurin:21-jdk
```

 
**Local Environment:**  
- DevPod Version: 0.5.4
- Operating System: mac
- ARCH of the OS: ARM64

**DevPod Provider:**  
- Local/remote provider: docker | ssh

**Anything else we need to know?**  
no.
