### ISSUE TITLE
Password field is shown in clear text when adding a new workspace

### ISSUE THREAD

**Issue by havardAasen** [loft-sh/devpod#975]
**What happened?**  
Using a provider that has a password field in `provider.yaml`. This password is shown in clear text when I create a new workspace.
![new_workspace](https://github.com/loft-sh/devpod/assets/30108525/bbb8922e-ecfb-4e28-a552-00765e0f357f)

If editing, the password field is masked correctly.
![new_workspace-edit_provider](https://github.com/loft-sh/devpod/assets/30108525/a95c0f56-b772-43a9-bd37-04325c245afc)

**What did you expect to happen instead?**  
The password field should be masked.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
- Add a provider with a password field.
- Make sure there is text in the password field
- Create a new workspace.
- Hover over the provider.

The specific field has this in the `provider.yaml`:
``` yaml
UIA_TOKEN:
  description: Token to authenticate with UiA.
  type: string
  required: true
  password: true
  global: true
```

**Local Environment:**  
- DevPod Version: `devpod 0.5.4`
- Operating System: Linux
- ARCH of the OS: AMD64 

**DevPod Provider:**  
I'm using a custom provider, but any provider with a password field should do.
